# Recommended Daily Allowances by (age_range, sex, special_condition)
# Values are DAILY targets per person
RDA_TABLE: dict[tuple[str, str, str], dict[str, float | int | str]] = {
    ("adult", "male", "none"): {
        "calories_kcal": 2200,
        "protein_g": 56,
        "fiber_g": 38,
        "sodium_mg": 2300,
        "potassium_mg": 3400,
        "calcium_mg": 1000,
        "iron_mg": 8,
        "folate_mcg": 400,
        "vitamin_d_iu": 600,
        "omega3_g": 1.6,
        "carbs_g": 275,
        "fat_g": 78,
        "saturated_fat_g": 22,
        "glycemic_load_target": "medium",
    },
    ("adult", "female", "none"): {
        "calories_kcal": 1800,
        "protein_g": 46,
        "fiber_g": 25,
        "sodium_mg": 2300,
        "potassium_mg": 2600,
        "calcium_mg": 1000,
        "iron_mg": 18,
        "folate_mcg": 400,
        "vitamin_d_iu": 600,
        "omega3_g": 1.1,
        "carbs_g": 225,
        "fat_g": 60,
        "saturated_fat_g": 20,
        "glycemic_load_target": "medium",
    },
    ("adult", "female", "pregnancy"): {
        "calories_kcal": 2200,
        "protein_g": 71,
        "fiber_g": 28,
        "sodium_mg": 2300,
        "potassium_mg": 2900,
        "calcium_mg": 1000,
        "iron_mg": 27,
        "folate_mcg": 600,
        "vitamin_d_iu": 600,
        "omega3_g": 1.4,
        "carbs_g": 275,
        "fat_g": 70,
        "saturated_fat_g": 20,
        "glycemic_load_target": "medium",
    },
    ("adult", "female", "postpartum"): {
        "calories_kcal": 2500,
        "protein_g": 71,
        "fiber_g": 29,
        "sodium_mg": 2300,
        "potassium_mg": 2800,
        "calcium_mg": 1000,
        "iron_mg": 9,
        "folate_mcg": 500,
        "vitamin_d_iu": 600,
        "omega3_g": 1.3,
        "carbs_g": 290,
        "fat_g": 78,
        "saturated_fat_g": 20,
        "glycemic_load_target": "medium",
    },
    ("child_4_8", "any", "none"): {
        "calories_kcal": 1400,
        "protein_g": 19,
        "fiber_g": 20,
        "sodium_mg": 1500,
        "potassium_mg": 2300,
        "calcium_mg": 1000,
        "iron_mg": 10,
        "folate_mcg": 200,
        "vitamin_d_iu": 600,
        "omega3_g": 0.9,
        "carbs_g": 175,
        "fat_g": 46,
        "saturated_fat_g": 15,
        "glycemic_load_target": "medium",
    },
    ("child_9_13", "any", "none"): {
        "calories_kcal": 1600,
        "protein_g": 34,
        "fiber_g": 26,
        "sodium_mg": 1800,
        "potassium_mg": 2500,
        "calcium_mg": 1300,
        "iron_mg": 8,
        "folate_mcg": 300,
        "vitamin_d_iu": 600,
        "omega3_g": 1.0,
        "carbs_g": 200,
        "fat_g": 53,
        "saturated_fat_g": 17,
        "glycemic_load_target": "medium",
    },
    ("elder_65plus", "male", "none"): {
        "calories_kcal": 2000,
        "protein_g": 56,
        "fiber_g": 30,
        "sodium_mg": 2300,
        "potassium_mg": 3400,
        "calcium_mg": 1200,
        "iron_mg": 8,
        "folate_mcg": 400,
        "vitamin_d_iu": 800,
        "omega3_g": 1.6,
        "carbs_g": 250,
        "fat_g": 67,
        "saturated_fat_g": 20,
        "glycemic_load_target": "medium",
    },
}

CONDITION_MODIFIERS: dict[str, dict[str, float | str]] = {
    "diabetes": {
        "fiber_g": 10,
        "carbs_g": -50,
        "glycemic_load_target": "low",
        "sodium_mg": 0,
        "saturated_fat_g": -5,
    },
    "hypertension": {
        "sodium_mg": -800,
        "potassium_mg": 400,
        "calcium_mg": 200,
        "saturated_fat_g": -5,
    },
    "iron_deficiency": {
        "iron_mg": 9,
    },
    "high_cholesterol": {
        "fiber_g": 5,
        "saturated_fat_g": -8,
        "omega3_g": 0.5,
    },
    "obesity": {
        "calories_kcal": -300,
        "fiber_g": 5,
        "protein_g": 10,
    },
    "kidney_disease": {
        "potassium_mg": -800,
        "sodium_mg": -500,
        "protein_g": -15,
    },
}

FOOD_PRICES: dict[str, float] = {
    "dried_lentils_lb": 1.49,
    "dried_beans_lb": 1.29,
    "canned_beans_15oz": 1.09,
    "brown_rice_lb": 1.39,
    "oats_rolled_lb": 1.29,
    "eggs_dozen": 3.49,
    "canned_sardines_can": 1.79,
    "frozen_fish_fillet_lb": 4.99,
    "chicken_thighs_lb": 2.29,
    "ground_turkey_lb": 4.49,
    "canned_tuna_5oz": 1.49,
    "whole_milk_gallon": 4.29,
    "lowfat_yogurt_6oz": 0.99,
    "frozen_spinach_10oz": 1.79,
    "fresh_banana_lb": 0.59,
    "sweet_potato_lb": 0.99,
    "broccoli_lb": 1.79,
    "carrots_bag_lb": 1.29,
    "canned_tomatoes_14oz": 1.09,
    "whole_wheat_bread_loaf": 3.49,
    "peanut_butter_16oz": 2.99,
    "olive_oil_bottle": 5.99,
    "onions_lb": 0.79,
    "garlic_head": 0.79,
}

WIC_ELIGIBLE_CATEGORIES: list[str] = [
    "infant_formula",
    "cereal_fortified",
    "juice_100pct",
    "milk",
    "eggs",
    "cheese",
    "legumes_dried",
    "peanut_butter",
    "whole_grains",
    "fruits_vegetables_fresh",
    "canned_fish",
    "tofu",
]

SNAP_WEEKLY_MAX: dict[int, int] = {
    1: 73,
    2: 134,
    3: 192,
    4: 244,
    5: 290,
    6: 348,
    7: 384,
    8: 439,
}
